### ISSUE TITLE
Piano di progetto (che contiene costi attesi, osservati nel primo periodo, obiettivi raggiunti e da raggiungere)

### ISSUE THREAD

**Issue by Mallow00** [Club-Swendwich/Documenti#21]

**Comment by samuelepozzebon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Piano di progetto (che contiene costi attesi, osservati nel primo periodo, obbiettivi raggiunti e da raggiungere)](https://trello.com/c/yLHhYoqp/1-piano-di-progetto-che-contiene-costi-attesi-osservati-nel-primo-periodo-obbiettivi-raggiunti-e-da-raggiungere)
