### ISSUE TITLE
Piano di qualifica (specifica degli obiettivi di qualità, cruscotto)

### ISSUE THREAD

**Issue by Mallow00** [Club-Swendwich/Documenti#22]

**Comment by samuelepozzebon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Piano di qualifica (specifica degli obbiettivi di qualità, cruscotto)](https://trello.com/c/Ixqi8AXM/2-piano-di-qualifica-specifica-degli-obbiettivi-di-qualit%C3%A0-cruscotto)
