### ISSUE TITLE
Verbale 007-01_12_21-riunione

### ISSUE THREAD

**Issue by ValentinaBeni** [Club-Swendwich/Documenti#24]

**Comment by Mallow00** [comment]
Documento approvato

**Comment by samuelepozzebon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #24: Verbale 007-01_12_2021-riunione](https://trello.com/c/ogr6jleN/6-issue-24-verbale-007-01122021-riunione)
