### ISSUE TITLE
Aggiornare sezione 1.3 "Richiedere la verifica di un documento" sul documento Way of Working

### ISSUE THREAD

**Issue by Mallow00** [Club-Swendwich/Documenti#25]
Essendo passati da GitHub a Trello è necessario aggiornare quella sezione.

**Comment by samuelepozzebon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #25: Aggiornare sezione 1.3 "Richiedere la verifica di un documento" sul documento Way of Working](https://trello.com/c/T2woXopi/10-issue-25-aggiornare-sezione-13-richiedere-la-verifica-di-un-documento-sul-documento-way-of-working)
